using AIAgents.Core.Configuration;
using AIAgents.Core.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AIAgents.Core.Services;

/// <summary>
/// Loads relevant .agent/ documentation for a given work item.
/// Uses keyword matching to select only the feature docs that are relevant,
/// avoiding loading everything (token limits).
/// </summary>
public sealed class CodebaseContextLoader : ICodebaseContextProvider
{
    private readonly IGitOperations _gitOps;
    private readonly CodebaseDocumentationOptions _options;
    private readonly ILogger<CodebaseContextLoader> _logger;

    // Core files always considered for loading (in priority order)
    private static readonly string[] s_coreFiles =
    {
        "CONTEXT_INDEX.md",
        "CODING_STANDARDS.md",
        "TECH_STACK.md"
    };

    // Supplementary files loaded on keyword match
    private static readonly Dictionary<string[], string> s_keywordFileMap = new()
    {
        { new[] { "database", "schema", "table", "migration", "entity", "sql", "query", "data model" }, "DATABASE_SCHEMA.md" },
        { new[] { "api", "endpoint", "rest", "graphql", "controller", "route", "http" }, "API_REFERENCE.md" },
        { new[] { "deploy", "pipeline", "ci/cd", "release", "infrastructure", "terraform" }, "DEPLOYMENT.md" },
        { new[] { "test", "unit test", "integration test", "e2e", "coverage", "mock" }, "TESTING_STRATEGY.md" },
        { new[] { "pattern", "convention", "how to", "standard", "template" }, "COMMON_PATTERNS.md" },
        { new[] { "architect", "design", "diagram", "flow", "component", "layer" }, "ARCHITECTURE.md" }
    };

    public CodebaseContextLoader(
        IGitOperations gitOps,
        IOptions<CodebaseDocumentationOptions> options,
        ILogger<CodebaseContextLoader> logger)
    {
        _gitOps = gitOps;
        _options = options.Value;
        _logger = logger;
    }

    public async Task<bool> HasCodebaseDocumentationAsync(
        string repositoryPath,
        CancellationToken cancellationToken = default)
    {
        var indexPath = Path.Combine(_options.OutputFolder, "CONTEXT_INDEX.md");
        var content = await _gitOps.ReadFileAsync(repositoryPath, indexPath, cancellationToken);
        return !string.IsNullOrWhiteSpace(content);
    }

    public async Task<string> LoadRelevantContextAsync(
        string repositoryPath,
        string workItemTitle,
        string? workItemDescription,
        CancellationToken cancellationToken = default)
    {
        if (!await HasCodebaseDocumentationAsync(repositoryPath, cancellationToken))
        {
            _logger.LogDebug("No .agent/ documentation found in repository");
            return string.Empty;
        }

        var searchText = $"{workItemTitle} {workItemDescription}".ToLowerInvariant();
        var sections = new List<string>();

        // 1. Always load core files
        foreach (var coreFile in s_coreFiles)
        {
            var path = Path.Combine(_options.OutputFolder, coreFile);
            var content = await _gitOps.ReadFileAsync(repositoryPath, path, cancellationToken);
            if (!string.IsNullOrWhiteSpace(content))
            {
                sections.Add($"<!-- {coreFile} -->\n{content}");
                _logger.LogDebug("Loaded core context: {File}", coreFile);
            }
        }

        // 2. Load supplementary files based on keyword match
        foreach (var (keywords, fileName) in s_keywordFileMap)
        {
            if (keywords.Any(kw => searchText.Contains(kw, StringComparison.OrdinalIgnoreCase)))
            {
                var path = Path.Combine(_options.OutputFolder, fileName);
                var content = await _gitOps.ReadFileAsync(repositoryPath, path, cancellationToken);
                if (!string.IsNullOrWhiteSpace(content))
                {
                    sections.Add($"<!-- {fileName} -->\n{content}");
                    _logger.LogDebug("Loaded keyword-matched context: {File}", fileName);
                }
            }
        }

        // 3. Load relevant FEATURES/*.md files
        var featuresDocs = await LoadRelevantFeaturesAsync(
            repositoryPath, searchText, cancellationToken);
        sections.AddRange(featuresDocs);

        if (sections.Count == 0)
        {
            return string.Empty;
        }

        var result = "## Codebase Context\n" +
                     "The following documentation was generated by analyzing the codebase. " +
                     "Follow these patterns and conventions when generating code.\n\n" +
                     string.Join("\n\n---\n\n", sections);

        _logger.LogInformation(
            "Loaded {SectionCount} context sections ({CharCount:N0} chars) for work item",
            sections.Count, result.Length);

        return result;
    }

    private async Task<List<string>> LoadRelevantFeaturesAsync(
        string repositoryPath,
        string searchText,
        CancellationToken cancellationToken)
    {
        var results = new List<string>();
        var featuresDir = Path.Combine(_options.OutputFolder, "FEATURES");
        var allFiles = await _gitOps.ListFilesAsync(repositoryPath, cancellationToken);

        var featureFiles = allFiles
            .Where(f => f.StartsWith(featuresDir.Replace('\\', '/'), StringComparison.OrdinalIgnoreCase) ||
                        f.StartsWith(featuresDir, StringComparison.OrdinalIgnoreCase))
            .Where(f => f.EndsWith(".md", StringComparison.OrdinalIgnoreCase))
            .ToList();

        foreach (var featureFile in featureFiles)
        {
            // Extract feature name from filename for keyword matching
            var fileName = Path.GetFileNameWithoutExtension(featureFile);
            var featureName = fileName.Replace("-", " ").Replace("_", " ").ToLowerInvariant();

            // Match if the feature name appears in the work item text,
            // or if any word in the feature name appears in the search text
            var featureWords = featureName.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            if (featureWords.Any(w => w.Length > 3 && searchText.Contains(w, StringComparison.OrdinalIgnoreCase)))
            {
                var content = await _gitOps.ReadFileAsync(repositoryPath, featureFile, cancellationToken);
                if (!string.IsNullOrWhiteSpace(content))
                {
                    results.Add($"<!-- FEATURES/{Path.GetFileName(featureFile)} -->\n{content}");
                    _logger.LogDebug("Loaded feature context: {File}", featureFile);
                }
            }
        }

        return results;
    }
}
