namespace AIAgents.Core.Configuration;

/// <summary>
/// Optional configuration for SaaS Mode integration with adom8.dev.
/// When <see cref="Enabled"/> is true the agent engine will:
///   1. Report real-time run status back to the SaaS dashboard.
///   2. (Future) Resolve AI / GitHub API keys from the SaaS secrets API
///      instead of reading them from the local Key Vault.
///
/// Bound to the "SaaS" configuration section.
/// When not present / Enabled = false, the engine operates fully standalone.
/// </summary>
public sealed class SaasOptions
{
    public const string SectionName = "SaaS";

    /// <summary>
    /// When false (default) all SaaS integration is disabled. No network
    /// calls are made to the SaaS API. Safe to leave unconfigured for
    /// fully standalone / OSS deployments.
    /// </summary>
    public bool Enabled { get; init; } = false;

    /// <summary>
    /// The base URL of the SaaS dashboard, e.g. "https://app.adom8.dev".
    /// Required when Enabled = true.
    /// </summary>
    public string? BaseUrl { get; init; }

    /// <summary>
    /// The per-project integration key used to authenticate callbacks sent
    /// to the SaaS. Generated by the SaaS when the project is created and
    /// stored in the Function App settings as "SaaS:IntegrationKey".
    /// Sent as the "x-saas-integration-key" request header.
    /// </summary>
    public string? IntegrationKey { get; init; }

    /// <summary>
    /// The SaaS-assigned project ID ─ used so the SaaS can look up the
    /// correct PipelineRun records when a callback arrives.
    /// </summary>
    public string? ProjectId { get; init; }
}
