namespace AIAgents.Core.Constants;

/// <summary>
/// Azure DevOps custom field reference names and JSON patch paths.
/// These map to custom fields added to the "Agile - AI Agents" inherited process
/// on the User Story work item type.
/// 
/// ADO auto-generates reference names from field display names using the pattern:
///   "Custom." + PascalCase(DisplayName with spaces removed)
/// 
/// Fields are grouped in the "AI Agent Settings" group on the Details page.
/// </summary>
public static class CustomFieldNames
{
    // ── Input Fields (set by the user per story) ────────────────────
    
    /// <summary>
    /// AI Autonomy Level picklist (integer values 1-5).
    /// Controls how far the pipeline runs automatically (1-5).
    /// Stored as Picklist(integer).
    /// </summary>
    public const string AutonomyLevel = "Custom.AutonomyLevel";
    
    /// <summary>
    /// Minimum review score (0-100) required for auto-merge at Levels 4-5.
    /// </summary>
    public const string MinimumReviewScore = "Custom.AIMinimumReviewScore";

    // ── Per-Story Model Override Fields ─────────────────────────────
    // These fields let users override the AI model on a per-story basis.
    // When blank, the system falls back to config-level defaults.

    /// <summary>
    /// Model tier preset: "Standard", "Premium", or "Economy".
    /// Maps to pre-configured model sets defined in AI:ModelTiers config.
    /// </summary>
    public const string ModelTier = "Custom.AIModelTier";

    /// <summary>Override model for the Planning agent (e.g., "claude-opus-4-20250514").</summary>
    public const string PlanningModel = "Custom.AIPlanningModel";

    /// <summary>Override model for the Coding agent (e.g., "codex-mini-latest").</summary>
    public const string CodingModel = "Custom.AICodingModel";

    /// <summary>Override model for the Testing agent (e.g., "gpt-4o-mini").</summary>
    public const string TestingModel = "Custom.AITestingModel";

    /// <summary>Override model for the Review agent (e.g., "claude-sonnet-4-20250514").</summary>
    public const string ReviewModel = "Custom.AIReviewModel";

    /// <summary>Override model for the Documentation agent (e.g., "gemini-2.0-flash").</summary>
    public const string DocumentationModel = "Custom.AIDocumentationModel";

    /// <summary>
    /// Per-story coding provider override: "Auto", "Agentic", or "Copilot".
    /// When set, overrides the global Copilot:Mode setting for this story.
    /// "Auto" = use global config, "Agentic" = force built-in loop, "Copilot" = force Copilot agent.
    /// </summary>
    public const string CodingProvider = "Custom.AICodingProvider";

    /// <summary>
    /// Optional per-story GitHub user/account alias used for PAT routing.
    /// When blank, runtime falls back to the default GitHub token.
    /// </summary>
    public const string GitHubUserAccount = "Custom.GitHubUserAccount";

    // ── Output Fields (written by agents during processing) ─────────

    /// <summary>
    /// Total tokens consumed across all agents in the pipeline.
    /// </summary>
    public const string TokensUsed = "Custom.AITokensUsed";
    
    /// <summary>
    /// Estimated cost in USD for all AI API calls.
    /// Stored as a string formatted "$0.0000".
    /// </summary>
    public const string Cost = "Custom.AICost";
    
    /// <summary>
    /// Story complexity classification based on total token usage: XS, S, M, L, XL.
    /// </summary>
    public const string Complexity = "Custom.AIComplexity";
    
    /// <summary>
    /// Per-agent model summary (e.g., "Planning: gpt-4o, Coding: claude-opus, Review: gpt-4o-mini").
    /// Shows which AI model each agent used during the pipeline.
    /// </summary>
    public const string Model = "Custom.AIModel";
    
    /// <summary>
    /// Code review score (0-100) from the Review agent.
    /// </summary>
    public const string ReviewScore = "Custom.AIReviewScore";
    
    /// <summary>
    /// Total pipeline processing time in seconds.
    /// </summary>
    public const string ProcessingTime = "Custom.AIProcessingTime";
    
    /// <summary>
    /// Number of source code files generated by the Coding agent.
    /// </summary>
    public const string FilesGenerated = "Custom.AIFilesGenerated";
    
    /// <summary>
    /// Number of test files generated by the Testing agent.
    /// </summary>
    public const string TestsGenerated = "Custom.AITestsGenerated";
    
    /// <summary>
    /// Pull request number created by the Documentation agent.
    /// </summary>
    public const string PRNumber = "Custom.AIPRNumber";
    
    /// <summary>
    /// Name of the last agent that processed this story.
    /// </summary>
    public const string LastAgent = "Custom.AILastAgent";

    /// <summary>
    /// Name of the AI agent currently working this story.
    /// Kept blank when no AI agent is actively processing.
    /// </summary>
    public const string CurrentAIAgent = "Custom.CurrentAIAgent";
    
    /// <summary>
    /// Number of critical issues found during code review.
    /// </summary>
    public const string CriticalIssues = "Custom.AICriticalIssues";
    
    /// <summary>
    /// Final deployment decision (e.g., "Auto-merged", "Assigned for human review").
    /// </summary>
    public const string DeploymentDecision = "Custom.AIDeploymentDecision";

    // ── JSON Patch Paths (for UpdateWorkItemFieldAsync) ─────────────

    public static class Paths
    {
        public const string AutonomyLevel = "/fields/" + CustomFieldNames.AutonomyLevel;
        public const string MinimumReviewScore = "/fields/" + CustomFieldNames.MinimumReviewScore;
        public const string TokensUsed = "/fields/" + CustomFieldNames.TokensUsed;
        public const string Cost = "/fields/" + CustomFieldNames.Cost;
        public const string Complexity = "/fields/" + CustomFieldNames.Complexity;
        public const string Model = "/fields/" + CustomFieldNames.Model;
        public const string ReviewScore = "/fields/" + CustomFieldNames.ReviewScore;
        public const string ProcessingTime = "/fields/" + CustomFieldNames.ProcessingTime;
        public const string FilesGenerated = "/fields/" + CustomFieldNames.FilesGenerated;
        public const string TestsGenerated = "/fields/" + CustomFieldNames.TestsGenerated;
        public const string PRNumber = "/fields/" + CustomFieldNames.PRNumber;
        public const string LastAgent = "/fields/" + CustomFieldNames.LastAgent;
        public const string CurrentAIAgent = "/fields/" + CustomFieldNames.CurrentAIAgent;
        public const string CriticalIssues = "/fields/" + CustomFieldNames.CriticalIssues;
        public const string DeploymentDecision = "/fields/" + CustomFieldNames.DeploymentDecision;

        // Per-story model override paths
        public const string ModelTier = "/fields/" + CustomFieldNames.ModelTier;
        public const string PlanningModel = "/fields/" + CustomFieldNames.PlanningModel;
        public const string CodingModel = "/fields/" + CustomFieldNames.CodingModel;
        public const string TestingModel = "/fields/" + CustomFieldNames.TestingModel;
        public const string ReviewModel = "/fields/" + CustomFieldNames.ReviewModel;
        public const string DocumentationModel = "/fields/" + CustomFieldNames.DocumentationModel;
        public const string CodingProvider = "/fields/" + CustomFieldNames.CodingProvider;
        public const string GitHubUserAccount = "/fields/" + CustomFieldNames.GitHubUserAccount;
    }
}
