using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using AIAgents.Core.Configuration;
using AIAgents.Core.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AIAgents.Functions.Services;

/// <summary>
/// Implementation of <see cref="ISaasCallbackService"/> that posts real-time
/// agent run status updates to the adom8.dev SaaS dashboard.
///
/// When SaaS Mode is disabled (SaaS:Enabled = false / not configured) every
/// method is a no-op so the rest of the engine is unaffected.
///
/// Authentication: each request carries the per-project integration key in
/// the "x-saas-integration-key" header. This key is generated by the SaaS
/// when a project is registered and stored in Key Vault (via the onboarding
/// pipeline). It is never shared between projects.
/// </summary>
public sealed class SaasCallbackService : ISaasCallbackService
{
    private readonly SaasOptions _options;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<SaasCallbackService> _logger;

    private bool IsEnabled => _options.Enabled
        && !string.IsNullOrWhiteSpace(_options.BaseUrl)
        && !string.IsNullOrWhiteSpace(_options.IntegrationKey);

    public SaasCallbackService(
        IOptions<SaasOptions> options,
        IHttpClientFactory httpClientFactory,
        ILogger<SaasCallbackService> logger)
    {
        _options = options.Value;
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task ReportAgentStartedAsync(
        string correlationId,
        string agentType,
        CancellationToken cancellationToken = default)
    {
        if (!IsEnabled) return;

        // correlationId format from SaaS queue producer: "<pipelineRunId>:<agentRunId>"
        if (!TryParseCorrelationId(correlationId, out var pipelineRunId, out _)) return;

        await PostCallbackAsync(new AgentCallbackPayload
        {
            PipelineRunId = pipelineRunId,
            AgentType = agentType,
            Status = "IN_PROGRESS",
        }, cancellationToken);
    }

    /// <inheritdoc />
    public async Task ReportAgentCompletedAsync(
        string correlationId,
        string agentType,
        int inputTokens,
        int outputTokens,
        int durationMs,
        string? resultSummary = null,
        string? prUrl = null,
        int? prNumber = null,
        CancellationToken cancellationToken = default)
    {
        if (!IsEnabled) return;

        if (!TryParseCorrelationId(correlationId, out var pipelineRunId, out _)) return;

        await PostCallbackAsync(new AgentCallbackPayload
        {
            PipelineRunId = pipelineRunId,
            AgentType = agentType,
            Status = "COMPLETED",
            InputTokens = inputTokens,
            OutputTokens = outputTokens,
            DurationMs = durationMs,
            ResultSummary = resultSummary,
            PrUrl = prUrl,
            PrNumber = prNumber,
        }, cancellationToken);
    }

    /// <inheritdoc />
    public async Task ReportAgentFailedAsync(
        string correlationId,
        string agentType,
        string errorMessage,
        CancellationToken cancellationToken = default)
    {
        if (!IsEnabled) return;

        if (!TryParseCorrelationId(correlationId, out var pipelineRunId, out _)) return;

        await PostCallbackAsync(new AgentCallbackPayload
        {
            PipelineRunId = pipelineRunId,
            AgentType = agentType,
            Status = "FAILED",
            ErrorMessage = errorMessage,
        }, cancellationToken);
    }

    private async Task PostCallbackAsync(AgentCallbackPayload payload, CancellationToken cancellationToken)
    {
        var endpoint = $"{_options.BaseUrl!.TrimEnd('/')}/api/internal/agent-callback";

        try
        {
            using var client = _httpClientFactory.CreateClient("SaasCallback");
            using var request = new HttpRequestMessage(HttpMethod.Post, endpoint);
            request.Headers.Add("x-saas-integration-key", _options.IntegrationKey!);
            request.Content = JsonContent.Create(payload, options: new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            });

            using var response = await client.SendAsync(request, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync(cancellationToken);
                _logger.LogWarning(
                    "SaaS callback for {AgentType}/{PipelineRunId} returned {StatusCode}: {Body}",
                    payload.AgentType, payload.PipelineRunId, (int)response.StatusCode, body);
            }
        }
        catch (Exception ex)
        {
            // Never let callback failures break agent execution.
            _logger.LogWarning(ex,
                "SaaS callback failed for {AgentType}/{PipelineRunId} — continuing without update",
                payload.AgentType, payload.PipelineRunId);
        }
    }

    /// <summary>
    /// Parses the correlationId format used by the SaaS queue producer:
    /// "{pipelineRunId}:{agentRunId}"
    /// </summary>
    private static bool TryParseCorrelationId(
        string correlationId,
        out string pipelineRunId,
        out string agentRunId)
    {
        pipelineRunId = string.Empty;
        agentRunId = string.Empty;

        if (string.IsNullOrWhiteSpace(correlationId)) return false;

        var colonIndex = correlationId.IndexOf(':', StringComparison.Ordinal);
        if (colonIndex < 1 || colonIndex >= correlationId.Length - 1) return false;

        pipelineRunId = correlationId[..colonIndex];
        agentRunId = correlationId[(colonIndex + 1)..];
        return true;
    }

    private sealed class AgentCallbackPayload
    {
        public string PipelineRunId { get; init; } = string.Empty;
        public string AgentType { get; init; } = string.Empty;
        public string Status { get; init; } = string.Empty;
        public string? ResultSummary { get; init; }
        public string? ErrorMessage { get; init; }
        public int InputTokens { get; init; }
        public int OutputTokens { get; init; }
        public int? DurationMs { get; init; }
        public string? PrUrl { get; init; }
        public int? PrNumber { get; init; }
    }
}
